import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import Header from './header'
import { PrimeReactProvider } from 'primereact/api';
import FooterComponents from "./components/footerComponents/index";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Embassy of Burkina Faso in India",
    description: "Generated by create next app",
};

export default async function LocaleLayout({
    children,
    params
}: {
    children: React.ReactNode;
    params: Promise<{ locale: string }>;
}) {
    const { locale } = await params;
    const messages = await getMessages();

    return (
        <html lang={locale}>
            <body
                className={` bg-repeat-x bg-[length:50%_auto] h-full`}  >
                <PrimeReactProvider>
            
                <NextIntlClientProvider messages={messages}>
                    <Header/>
                    {children}
                       <FooterComponents />
                </NextIntlClientProvider>
                </PrimeReactProvider>
            </body>
         
        </html>
    );
}
